Added google scraper tool
Wizwert/Chandigarh pull request #4
Opened 2020-08-01 13:16 UTC by rodde

2020-08-01 17:22 UTC, Wizwert requested changes
I think we need to delete the now extra code from the file

2020-08-01 17:22 UTC, Wizwert commented on src/searchSite.ts
> +  const scraper = require('puppeteer-google-scraper');
We can do this as an import statement instead
```suggestion
  import scraper from 'puppeteer-google-scraper';
```

2020-08-01 17:22 UTC, Wizwert commented on src/searchSite.ts
> +  scraper(searchTerm, {limit: Number.MAX_VALUE, headless: true}).then((d: any) => {
We can do this using await
```suggestion
  const result = await scraper(searchTerm, {limit: Number.MAX_VALUE, headless: true});

```

2020-08-01 17:22 UTC, Wizwert commented on src/searchSite.ts
>    const links = await page.$$eval('a', (as) => as.map((a) => (a as HTMLAnchorElement).href));
We can scrap all the existing puppeter code in favor of using the library, we don't need to create our own browser object or any of that.

2020-08-02 09:21 UTC, rodde commented
That looks great! Are these changes you've already pushed or are these
changes that I would normally make?

On Sat, Aug 1, 2020 at 6:22 PM Will <notifications@github.com> wrote:

> *@Wizwert* requested changes on this pull request.
>
> I think we need to delete the now extra code from the file
> ------------------------------
>
> In src/searchSite.ts
> <https://github.com/Wizwert/Chandigarh/pull/4#discussion_r463981885>:
>
> >
>
> -  const pageLinks = links.filter((l) => l !== '' && (new URL(l)).hostname == domain).map((l) => new URL(l));
>
> -
>
> -  page.pdf({path: './search.pdf'});
>
> +  const urls: URL[] = [];
>
> +  const scraper = require('puppeteer-google-scraper');
>
>
> We can do this as an import statement instead
> ⬇️ Suggested change
>
> -  const scraper = require('puppeteer-google-scraper');
>
> +  import scraper from 'puppeteer-google-scraper';
>
>
> ------------------------------
>
> In src/searchSite.ts
> <https://github.com/Wizwert/Chandigarh/pull/4#discussion_r463981990>:
>
> >
>
> -  const pageLinks = links.filter((l) => l !== '' && (new URL(l)).hostname == domain).map((l) => new URL(l));
>
> -
>
> -  page.pdf({path: './search.pdf'});
>
> +  const urls: URL[] = [];
>
> +  const scraper = require('puppeteer-google-scraper');
>
> +  scraper(searchTerm, {limit: Number.MAX_VALUE, headless: true}).then((d: any) => {
>
>
> We can do this using await
> ⬇️ Suggested change
>
> -  scraper(searchTerm, {limit: Number.MAX_VALUE, headless: true}).then((d: any) => {
>
> +  const result = await scraper(searchTerm, {limit: Number.MAX_VALUE, headless: true});
>
>
> ------------------------------
>
> In src/searchSite.ts
> <https://github.com/Wizwert/Chandigarh/pull/4#discussion_r463982059>:
>
> > @@ -21,15 +21,17 @@ const searchSite = async (domain: string, searchTerm: string) : Promise<URL[]> =
>
>      page.keyboard.press('Enter'),
>
>    ]);
>
>
>
> +  // TODO: Navigate all the pages not just first.
>
>    const links = await page.$$eval('a', (as) => as.map((a) => (a as HTMLAnchorElement).href));
>
>
> We can scrap all the existing puppeter code in favor of using the library,
> we don't need to create our own browser object or any of that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Wizwert/Chandigarh/pull/4#pullrequestreview-459591640>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2QY6AG6JUZL6CXDVHV2CLR6RFMRANCNFSM4PRXTTGA>
> .
>

2020-08-02 11:52 UTC, Wizwert commented
> That looks great! Are these changes you've already pushed or are these changes that I would normally make?
> […](#)
> On Sat, Aug 1, 2020 at 6:22 PM Will ***@***.***> wrote: *@Wizwert* requested changes on this pull request. I think we need to delete the now extra code from the file ------------------------------ In src/searchSite.ts <[#4 (comment)](https://github.com/Wizwert/Chandigarh/pull/4#discussion_r463981885)>: > - const pageLinks = links.filter((l) => l !== '' && (new URL(l)).hostname == domain).map((l) => new URL(l)); - - page.pdf({path: './search.pdf'}); + const urls: URL[] = []; + const scraper = require('puppeteer-google-scraper'); We can do this as an import statement instead ⬇️ Suggested change - const scraper = require('puppeteer-google-scraper'); + import scraper from 'puppeteer-google-scraper'; ------------------------------ In src/searchSite.ts <[#4 (comment)](https://github.com/Wizwert/Chandigarh/pull/4#discussion_r463981990)>: > - const pageLinks = links.filter((l) => l !== '' && (new URL(l)).hostname == domain).map((l) => new URL(l)); - - page.pdf({path: './search.pdf'}); + const urls: URL[] = []; + const scraper = require('puppeteer-google-scraper'); + scraper(searchTerm, {limit: Number.MAX_VALUE, headless: true}).then((d: any) => { We can do this using await ⬇️ Suggested change - scraper(searchTerm, {limit: Number.MAX_VALUE, headless: true}).then((d: any) => { + const result = await scraper(searchTerm, {limit: Number.MAX_VALUE, headless: true}); ------------------------------ In src/searchSite.ts <[#4 (comment)](https://github.com/Wizwert/Chandigarh/pull/4#discussion_r463982059)>: > @@ -21,15 +21,17 @@ const searchSite = async (domain: string, searchTerm: string) : Promise<URL[]> = page.keyboard.press('Enter'), ]); + // TODO: Navigate all the pages not just first. const links = await page.$$eval('a', (as) => as.map((a) => (a as HTMLAnchorElement).href)); We can scrap all the existing puppeter code in favor of using the library, we don't need to create our own browser object or any of that. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub <[#4 (review)](https://github.com/Wizwert/Chandigarh/pull/4#pullrequestreview-459591640)>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA2QY6AG6JUZL6CXDVHV2CLR6RFMRANCNFSM4PRXTTGA> .

These are just suggestions, to help illustrate. You'll have to make the changes yourself

2020-08-02 12:20 UTC, rodde commented
Alright, looked at this a little bit. Two things. I get an error trying to
import the google-scraper saying it could not find a type declaration. I
tried and npm install @types/puppeteer-google-scraper and no luck there.
Stack overflow says we can create a .d.ts file and declare it in that file,
and that's what I was planning to do unless you know of something better.
Second, we can pretty much get rid of the searchSite file if we're removing
the puppeteer code and just make the call to google-scraper whenever we
need the info. Thoughts?

On Sat, Aug 1, 2020 at 6:22 PM Will <notifications@github.com> wrote:

> *@Wizwert* requested changes on this pull request.
>
> I think we need to delete the now extra code from the file
> ------------------------------
>
> In src/searchSite.ts
> <https://github.com/Wizwert/Chandigarh/pull/4#discussion_r463981885>:
>
> >
>
> -  const pageLinks = links.filter((l) => l !== '' && (new URL(l)).hostname == domain).map((l) => new URL(l));
>
> -
>
> -  page.pdf({path: './search.pdf'});
>
> +  const urls: URL[] = [];
>
> +  const scraper = require('puppeteer-google-scraper');
>
>
> We can do this as an import statement instead
> ⬇️ Suggested change
>
> -  const scraper = require('puppeteer-google-scraper');
>
> +  import scraper from 'puppeteer-google-scraper';
>
>
> ------------------------------
>
> In src/searchSite.ts
> <https://github.com/Wizwert/Chandigarh/pull/4#discussion_r463981990>:
>
> >
>
> -  const pageLinks = links.filter((l) => l !== '' && (new URL(l)).hostname == domain).map((l) => new URL(l));
>
> -
>
> -  page.pdf({path: './search.pdf'});
>
> +  const urls: URL[] = [];
>
> +  const scraper = require('puppeteer-google-scraper');
>
> +  scraper(searchTerm, {limit: Number.MAX_VALUE, headless: true}).then((d: any) => {
>
>
> We can do this using await
> ⬇️ Suggested change
>
> -  scraper(searchTerm, {limit: Number.MAX_VALUE, headless: true}).then((d: any) => {
>
> +  const result = await scraper(searchTerm, {limit: Number.MAX_VALUE, headless: true});
>
>
> ------------------------------
>
> In src/searchSite.ts
> <https://github.com/Wizwert/Chandigarh/pull/4#discussion_r463982059>:
>
> > @@ -21,15 +21,17 @@ const searchSite = async (domain: string, searchTerm: string) : Promise<URL[]> =
>
>      page.keyboard.press('Enter'),
>
>    ]);
>
>
>
> +  // TODO: Navigate all the pages not just first.
>
>    const links = await page.$$eval('a', (as) => as.map((a) => (a as HTMLAnchorElement).href));
>
>
> We can scrap all the existing puppeter code in favor of using the library,
> we don't need to create our own browser object or any of that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Wizwert/Chandigarh/pull/4#pullrequestreview-459591640>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2QY6AG6JUZL6CXDVHV2CLR6RFMRANCNFSM4PRXTTGA>
> .
>

2020-08-03 15:48 UTC, Wizwert commented
My opinion would be to keep the file wrapping the third party lib. Just to keep it from leaking out into the rest of the app.

2020-08-08 13:45 UTC, rodde commented
Cleaned up the excess code.

2020-08-10 08:48 UTC, merged